all:
	gcc -o receiver_sigalrm receiver_sigalrm.c
	gcc -o receiver_select receiver_sigalrm.c
	gcc -o receiver_sockopt receiver_sigalrm.c
	gcc -o sender_sigalrm sender_sigalrm.c
	gcc -o sender_select sender_select.c
	gcc -o sender_sockopt sender_sockopt.c
